/**:
  ros__parameters:
    world_frame: "world"
    agent_frame: "base"
    # agent_prefix: "agent"

    pool_stl_file_name: "aqua_pool.stl"
    pool_origin_position: [0.87, 1.07, 0.2]

    kp: 1.0 # P-gain
    dt: 0.1 # [s]

    # field parameters
    # TODO: pool size
    grid_accuracy: [90, 34]
    x_limit: [-1.5, 3.0] # 4.5m
    y_limit: [0.2, 1.9] # 1.7m

agent0:
  robot:
    ros__parameters:
      init_position: [0.5, 0.0]

agent1:
  robot:
    ros__parameters:
      init_position: [0.0, 0.5]

agent2:
  robot:
    ros__parameters:
      init_position: [-0.5, 0.5]
