agent0:
  kinematic_agent:
    ros__parameters:
      init_position: [0.5, 0.0]
  identified_agent:
    ros__parameters:
      init_position: [0.5, 0.0]

agent1:
  kinematic_agent:
    ros__parameters:
      init_position: [0.0, 0.5]
  identified_agent:
    ros__parameters:
      init_position: [0.0, 0.5]

agent2:
  kinematic_agent:
    ros__parameters:
      init_position: [-0.5, 0.5]
  identified_agent:
    ros__parameters:
      init_position: [-0.5, 0.5]