agent0:
  ideal_agent:
    ros__parameters:
      init_position: [-1.0, 1.0]

agent1:
  ideal_agent:
    ros__parameters:
      init_position: [0.75, 1.5]    

agent2:
  ideal_agent:
    ros__parameters:
      init_position: [0.75, 0.5]
  
agent3:
  ideal_agent:
    ros__parameters:
      init_position: [2.5, 1.0]
  